# Generated by Django 4.2 on 2023-04-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('associacao', models.CharField(max_length=20)),
                ('data_nasc', models.DateField()),
                ('data_exped', models.DateField()),
                ('data_valid', models.DateField()),
                ('foto', models.ImageField(upload_to='carteiras')),
            ],
        ),
    ]
