# Generated by Django 4.2 on 2023-04-19 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='creaated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
