# Generated by Django 4.2 on 2023-04-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_carteira_creaated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carteira',
            old_name='creaated',
            new_name='created',
        ),
    ]
